[server]
server_addr = "170.106.109.105:999"

[auth]
username = "user1"
auth_code = "seeinp_7694c0274401a80bee398ccc5ec02071da8b01a244ae76792752fae46679e5be"

[tls]
enabled = true
skip_verify = true

[local]
bend_addr = ":65443"

[logging]
level = "info"
path = "logs"
max_size = 100
max_backups = 7
